// New editor/menu copy is kept together for the planned language selector.
export const editorText = {
  play: 'Játék',
  create: 'Új szoba',
  editor: 'Szerkesztő',
  roomsSoon: 'Elérhető szobák · hamarosan',
  backMain: 'Vissza a főmenübe',
  backPlay: 'Vissza a Játék menübe',
  intro: 'Rajzolj szabadon, időkorlát nélkül. A rajzod ezen az eszközön marad meg.',
  newDrawing: 'Új rajz',
  newDrawingTitle: 'Új rajzot kezdesz?',
  leaveTitle: 'Visszalépsz a menübe?',
  clearTitle: 'Törlöd a rajzot?',
  clear: 'Rajz törlése',
  clearMessage: 'A vászon kiürül. A törlést a Visszavonás gombbal visszacsinálhatod.',
  export: 'PNG letöltése',
  exportSize: 'PNG mérete',
  original: '32 × 32 · eredeti',
  enlarged: '256 × 256 · 8×',
  leave: 'Még nem töltötted le a rajz legutóbbi változatát. Visszalépsz? A rajz helyben megmarad.',
  leaveWithoutStorage: 'A böngésző nem tudta megőrizni a rajzot. Ha most visszalépsz, elveszhet. Válaszd a Mégsem gombot, és előbb töltsd le PNG-ként, vagy lépj vissza mentés nélkül.',
  leaveUnsaved: 'Visszalépés mentés nélkül',
  replace: 'Új, üres rajzot kezdesz? A jelenlegi rajz helyi példányát lecseréljük.',
  local: 'A rajz helyben megőrizve. PNG-t a letöltés gombbal készíthetsz.',
  downloaded: 'A PNG elkészült, a letöltést elindítottuk.',
  storageError: 'A böngésző nem tudja helyben megőrizni a rajzot. Kilépés előtt töltsd le PNG-ként.',
  exportError: 'Nem sikerült elkészíteni a PNG-t. Próbáld újra.',
  freeDrawing: 'Szabad rajzolás',
  localMode: 'Helyi szerkesztő',
} as const
