create table public.bug_reports (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  room_id bigint,
  room_code text,
  reporter_name text,
  category text not null default 'bug'
    check (category in ('bug', 'ui', 'connection', 'idea')),
  description text not null
    check (char_length(description) between 10 and 1500),
  steps text
    check (steps is null or char_length(steps) <= 1500),
  technical_context jsonb not null default '{}'::jsonb,
  status text not null default 'new'
    check (status in ('new', 'reviewed', 'fixed', 'closed'))
);

alter table public.bug_reports enable row level security;

revoke all on table public.bug_reports from anon, authenticated;
grant insert (
  user_id,
  room_id,
  room_code,
  reporter_name,
  category,
  description,
  steps,
  technical_context
) on table public.bug_reports to authenticated;
grant usage, select on sequence public.bug_reports_id_seq to authenticated;

create policy "Players can submit their own bug reports"
on public.bug_reports
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create index bug_reports_created_at_idx
on public.bug_reports (created_at desc);

comment on table public.bug_reports is
  'Private tester feedback. Browser clients may insert their own reports but cannot read reports.';
